### ISSUE TITLE
Create preset answers for the questionnaire (hard core, casual, or messng arond type answers automatically)

### ISSUE THREAD

**Issue by Jrs389** [cs3398-Ferengi-Finaglers/-CS3398-Ferengi-Finaglers-S2019-#79]

**Comment by LeanderDavis** [comment]
This turned out to be much more difficult than it seemed.  I worked on it for at least 5 to 6 hours and still have not figured it out.  Using general templated django is just copy paste but this required a bit of digging into using python directly to put entries into database
